title: "SalvatoreBrk - Embedded Systems Engineer"
description: "Electronic Engineer specializing in Embedded Systems, Firmware, and Automotive Safety."
theme: jekyll-theme-minimal
lang: en
author: "SalvatoreBrk"
